# -*- coding: utf-8 -*-
"""code_mycopy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvpOrENoTqq-e2zDrgOs2V6FUQjzUB6p
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score

# Load the dataset
filepath = 'BioMarkerCSV.csv'
data = pd.read_csv(filepath)

# Display the first few rows of the dataset
print(data.head())

X = data.drop(columns=['Phosphatidylserine_Level'])
#threshold
y = data['Phosphatidylserine_Level'].apply(lambda x: 1 if x > 10 else 0)
print("hi")
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=1000)
print("hi")
#Random Forest Classifier (paramters were given as sample on stack overflow)
rf_model = RandomForestClassifier(n_estimators=100,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1,
    oob_score=True)
rf_model.fit(X_train, y_train)
print("hi")
# Make predictions on the test set
y_pred = rf_model.predict(X_test)
print("hi")
# Calculate classification performance metrics
accuracy = accuracy_score(y_test, y_pred)
classification = classification_report(y_test, y_pred)

print("hi")
# Output the metrics
print(f"Accuracy scorei s: {accuracy}")
print(f"Classification reporte:\n{classification}")
